### ISSUE TITLE
Selected match seems to change on its own when two matches are played at the same time

### ISSUE THREAD

**Issue by DannyJJK** [cedricblondeau/world-cup-2022-cli-dashboard#12]
Version 1.1.0
API: worldcupjson.net

Today Netherlands vs Qatar are playing at the same time as Ecuador vs Senegal, I am trying to use this app to monitor the score of the one that I'm not watching on TV, but sometimes it switches to the other live match on its own.

Is there any way to stop this?

**Comment by cedricblondeau** [comment]
I suspect it was happening because games were sorted by _date_ in 1.1.0:
https://github.com/cedricblondeau/world-cup-2022-cli-dashboard/blob/447c6faef6406249b6f189dc76dd286db9fc2ace/ui/fetch.go#L39-L41

There were no guarantees that games with a similar date would always be in the same order.

In [1.2.0](https://github.com/cedricblondeau/world-cup-2022-cli-dashboard/releases/tag/v1.2.0), games are sorted by ID (unique):
https://github.com/cedricblondeau/world-cup-2022-cli-dashboard/blob/ed27c372b2f64b0da789b6018a7d5105d172df1a/data/worldcupjson/client.go#L95-L97

It might come with the side-effect of fixing this issue.
