### ISSUE TITLE
Flag Colors Incorrect

### ISSUE THREAD

**Issue by ssingh13-rms** [cedricblondeau/world-cup-2022-cli-dashboard#18]
First of all, absolutely incredible work! This project is incredible! 
Just wanted to share that the a few of the flags look off (particularly the red colour)
See screenshots below for Poland and Denmark

![Screenshot 2022-11-30 at 12 13 55 PM](https://user-images.githubusercontent.com/47655001/204726460-c6bea877-28c1-423d-ac8c-9ffb53b8f843.png)

![Screenshot 2022-11-30 at 12 13 46 PM](https://user-images.githubusercontent.com/47655001/204726467-1dfc4177-8014-44bf-9578-27fae29b49ff.png)

Also tried viewing it in a terminal without a background image (see example below for US flag)
![Screenshot 2022-11-30 at 12 17 46 PM](https://user-images.githubusercontent.com/47655001/204726988-fb480097-7bde-4d6b-8c88-76d62f6122ff.png)

**Comment by cedricblondeau** [comment]
For optimal results, it's recommended to use a terminal with **True Color (24-bit)** support.

My guess is that you're rendering the flags with a **256 colors** profile - which the dashboard is not optimized for.

It could happen because 1) the terminal does not support True Color or; 2) [lipgloss](https://github.com/charmbracelet/lipgloss#colors) can't detect True Color support.

If your terminal supports True Color, try setting `COLORTERM` to `truecolor`, `yes`, `true` or `24bit`?

E.g.

```bash
COLORTERM="truecolor" world-cup-2022-cli-dashboard
```
