### ISSUE TITLE
v1.3.0 Terminal now requires 160 cols/50 rows

### ISSUE THREAD

**Issue by DannyJJK** [cedricblondeau/world-cup-2022-cli-dashboard#27]
The readme no longer matches the required columns and rows needed to display the dashboard.

Previously I was able to view the dashboard with a fullscreen terminal, however I now need to reduce my text size to see it.

The readme says:

> For optimal results, it's recommended to use a terminal with:
> 
> - True Color (24-bit) support;
> - at least 102 columns and 35 rows.

However on v1.3.0 dashboard now says:
> ❌ Need at least 160 columns and 50 rows to render.
>
> Resize terminal or press q to quit.

This may not be a bug, but either the readme needs to match the new requirement, or can the requirement be put back to 102 columns and 35 rows, where certain information is hidden at this size?

**Comment by cedricblondeau** [comment]
Hi @DannyJJK. Good catch!

It's an intentional change. I added player stats in 1.3.0 (https://github.com/cedricblondeau/world-cup-2022-cli-dashboard/pull/26). 160x50 is the minimum for all the components to fully render.

<img width="1608" alt="Screenshot 2022-12-05 at 8 25 59 AM" src="https://user-images.githubusercontent.com/1479924/205648288-c46c6117-e740-46c5-9b5e-e1937eaedede.png">

This is a tradeoff. I prefer making sure the dashboard provides a great user experience for specific setups (i.e. colour profile and size) over supporting more setups with rendering issues.

I just updated the README to reflect the new requirement.

---

However, I also want to listen to feedback. If we think the requirement is too high, then we could make some other changes.

For the rows, we could:
1. Set min rows back to 35
2. If rows < 50, hide lineups or add ability to scroll (so we don't show partial lineups)

For the columns, the lineups are now tables and each row should fit in a single line. We could:
1. Decrease the player column width (currently 27 cols) and truncate the player name if it does not fit
2. Reduce the min columns

https://github.com/cedricblondeau/world-cup-2022-cli-dashboard/blob/0b27bcf7d8dfa6ef2ac61f7257da111bcccbfc77/ui/match/match.go#L130

I'm also very open to other ideas and would welcome a PR to implement these changes.

**Comment by DannyJJK** [comment]
I mainly opened the issue as I wasn't sure if it was accidental as the readme wasn't updated and the previous version hid certain elements on a smaller size. Thanks for the explanation, I'll close this issue for now but if someone else finds this annoying then it can be re-opened
